# Generated by Django 3.2.9 on 2023-09-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('period_tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodtracker',
            name='back_pain',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='periodtracker',
            name='food_cravings',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='periodtracker',
            name='headaches',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
