# Generated by Django 3.2.9 on 2023-09-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('period_tracker_app', '0002_auto_20230927_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodtracker',
            name='next_period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='periodtracker',
            name='ovulation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
