# Generated by Django 3.2.9 on 2023-10-05 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('period_tracker_app', '0003_auto_20230929_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mood_swings', models.BooleanField(default=False)),
                ('cramps', models.BooleanField(default=False)),
                ('headache', models.BooleanField(default=False)),
                ('backpain', models.BooleanField(default=False)),
                ('food_cravings', models.BooleanField(default=False)),
                ('vomiting', models.BooleanField(default=False)),
                ('irritation', models.BooleanField(default=False)),
                ('spotting', models.BooleanField(default=False)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
